# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  #
  # Python product dependencies
  #

  # Python API requirements
  - package-ecosystem: pip
    directory: "/src/bindings/python/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 3
    assignees:
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  # Model Optimizer requirements
  - package-ecosystem: pip
    directory: "/tools/mo"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "rkazants"
      - "andrei-kochin"
      - "jiwaszki"
      - "p-wysocki"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    versioning-strategy: increase-if-necessary

  # POT requirements
  - package-ecosystem: pip
    directory: "/tools/pot"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "AlexKoff88"
      - "KodiaqQ"
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  # benchmark_tool requirements
  - package-ecosystem: pip
    directory: "/tools/benchmark_tool"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "Wovchena"
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  #
  # Tests requirements for frontends
  #

  # PaddlePaddle FE tests requirements
  - package-ecosystem: pip
    directory: "/src/frontends/paddle/tests/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    assignees:
      - "ceciliapeng2011"
      - "meiyang-intel"
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  # ONNX FE tests requirements
  - package-ecosystem: pip
    directory: "/src/frontends/onnx/tests/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 3
    assignees:
      - "mbencer"
      - "tomdol"
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  # TensorFlow FE tests requirements
  - package-ecosystem: pip
    directory: "/src/frontends/tensorflow/tests/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "rkazants"
      - "jiwaszki"
      - "p-wysocki"
    versioning-strategy: increase-if-necessary

  # TensorFlow Lite FE tests requirements
  - package-ecosystem: pip
    directory: "/src/frontends/tensorflow_lite/tests/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "jane-intel"
      - "rkazants"
      - "jiwaszki"
      - "p-wysocki"
    versioning-strategy: increase-if-necessary

  #
  # Python Samples
  #

  - package-ecosystem: pip
    directory: "/samples/python/hello_reshape_ssd/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "Wovchena"
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  - package-ecosystem: pip
    directory: "/samples/python/classification_sample_async/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "Wovchena"
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  - package-ecosystem: pip
    directory: "/samples/python/benchmark/bert_benchmark/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "Wovchena"
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  - package-ecosystem: pip
    directory: "/samples/python/hello_classification/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 3
    assignees:
      - "Wovchena"
      - "jiwaszki"
      - "p-wysocki"
      - "rkazants"
    versioning-strategy: increase-if-necessary

  #
  # Github actions - CI
  #

  # Github actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    assignees:
      - "ilyachur"
      - "ilya-lavrenov"
    open-pull-requests-limit: 3
